export enum ERouteTable {
  ROOT = '/',
  SIGIN_IN = '/sign-in',
  SIGIN_UP = '/sign-up',
  VERIFY_ACCOUNT = '/verify-account',
  USER_INFORMATION = '/user-information',
  HOME = '/home',
  ONBOARDING = '/onboarding',
  ARTIST_DETAIL = '/artist-detail',
  PLAY_MUSIC = '/play-music',
  SEARCH_SCREEN = '/search',
  CATEGORY_DETAIL = '/category-detail',
  CATEGORY = '/category',
  ADD_SONG = '/add-song',
  ADD_SONG_ALBUM = '/add-song-album',
  ADD_SONG_ARTIST = '/add-song-artist',
  ADD_ARTIST = '/add-artist',
  LIBRARY_DETAIL = '/library-detail',
  ALBUM_DETAIL = '/album-detail',
  FAVORITE_DETAIL = '/favorite-detail',
  BOOK_DETAIL = '/book-detail',
  LIST_COMMENT = '/list-comment',
  READING_BOOK = '/reading-book',
  AI_UPDATE = '/ai-update',

  ACCOUNT_INFORMATION = '/account-information',
  EDIT_ACCOUNT = '/edit-account',
  SUBCRIPTION_PAKAGE = '/subcription-pakage',
  SETTING_SCREEN = '/setting',
  APP_OPTIONS = '/app-options',
  CONTENT_QUALITY = '/content-quality',
  DATA_SCREEN = '/data-screen',
  ABOUT_SCREEN = '/about-screen',
  PRIVACY_POLICY = '/privacy-policy',
  TERM_CONDITION = '/term-condition',
  SUPPORT = '/support',
}
